import serial.tools.list_ports

def declare_vars(self):
    self.MM = 0
    self.SS = 0
    self.froze_loop = 0  # prevent fly command when paused
    self.froze = 0  # prevent pause to be pressed multiple times
    self.pause_state = 0  # not at pause state
    self.mirror = 5  # used as flag in C-Python
    self.printer = 0
    self.set_motor = 0
    self.USB_CONNECTED = 0
    self.usb_connected = 1
    self.set_temp = 0
    self.set_fan = 0
    self.home_axis = 0
    self.usb_printing = 0
    self.rapid_pos = 0
    self.rapid_X = 0
    self.rapid_Y = 0
    self.rapid_Z = 0
    self.nozz_auto_tune = 0
    self.InvertX_tongle = 1
    self.InvertY_tongle = 1
    self.InvertZ_tongle = 1
    self.bl_toggle = 0
    self.BL_TOUCH_STATE = 0
    self.ABL_INTERPOLATION_TYPE = 0
    self.A = 0
    self.B = 0
    self.C = 0
    self.D = 0
    self.E = 0
    self.F = 0
    self.G = 0
    self.H = 0
    self.I = 0
    self.J = 0
    self.K = 0
    self.L = 0
    self.M = 0
    self.N = 0
    self.O = 0
    self.P = 0
    self.Q = 0
    self.R = 0
    self.S = 0
    self.T = 0
    self.U = 0
    self.V = 0
    self.W = 0
    self.Auto_P = 0
    self.Auto_I = 0
    self.Auto_D = 0
    self.update_temp = 0
    self.ABL = 0
    self.iterations = 1.0
    self.STPZ = 100
    self.ABL_Z_CENTER = 0
    self.ABL_Sample = 0
    self.plot_num = 0
    self.min = 0
    self.x_pos_last = 0
    self.stepx_direction = 1
    self.stepy_direction = 1
    self.stepz_direction = 1
    self.stepx_pos = 0
    self.stepy_pos = 0
    self.stepz_pos = 0
    self.x_overflow = 0
    self.sum_Xpos = 0
    self.sum_Ypos = 0
    self.sum_Zpos = 0
    self.x_overflow_last = 0
    self.y_pos_last = 0
    self.y_overflow = 0
    self.y_overflow_last = 0
    self.z_pos_last = 0
    self.z_overflow = 0
    self.z_overflow_last = 0
    self.int16_base = 0
    self.chosenPort = ""
    self.InvertX = 1
    self.InvertY = 1
    self.InvertZ = 1
    self.ports = serial.tools.list_ports.comports()
    self.comboBox.addItem("")
    for p in self.ports:
        self.comboBox.addItem(p.device)
