# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autotune.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoTune(object):
    def setupUi(self, AutoTune):
        AutoTune.setObjectName("AutoTune")
        AutoTune.resize(299, 149)
        AutoTune.setMinimumSize(QtCore.QSize(299, 140))
        AutoTune.setMaximumSize(QtCore.QSize(299, 149))
        AutoTune.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 63, 63);")
        self.frame_2 = QtWidgets.QFrame(AutoTune)
        self.frame_2.setGeometry(QtCore.QRect(9, 9, 281, 131))
        self.frame_2.setMinimumSize(QtCore.QSize(281, 131))
        self.frame_2.setMaximumSize(QtCore.QSize(281, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(95, 10, 90, 18))
        self.label.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(40, 34, 200, 50))
        self.frame_3.setMinimumSize(QtCore.QSize(200, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(200, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(30, 81, 220, 40))
        self.frame_4.setMinimumSize(QtCore.QSize(220, 40))
        self.frame_4.setMaximumSize(QtCore.QSize(220, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_autotune = QtWidgets.QPushButton(self.frame_4)
        self.ok_autotune.setMinimumSize(QtCore.QSize(80, 25))
        self.ok_autotune.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ok_autotune.setFont(font)
        self.ok_autotune.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.ok_autotune.setObjectName("ok_autotune")
        self.horizontalLayout.addWidget(self.ok_autotune)
        self.cancel_autotune = QtWidgets.QPushButton(self.frame_4)
        self.cancel_autotune.setMinimumSize(QtCore.QSize(80, 25))
        self.cancel_autotune.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_autotune.setFont(font)
        self.cancel_autotune.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.cancel_autotune.setObjectName("cancel_autotune")
        self.horizontalLayout.addWidget(self.cancel_autotune)

        self.retranslateUi(AutoTune)
        QtCore.QMetaObject.connectSlotsByName(AutoTune)

    def retranslateUi(self, AutoTune):
        _translate = QtCore.QCoreApplication.translate
        AutoTune.setWindowTitle(_translate("AutoTune", "Form"))
        self.label.setText(_translate("AutoTune", "Printer Name:"))
        self.label_2.setText(_translate("AutoTune", "P: 100"))
        self.label_3.setText(_translate("AutoTune", "I: 100"))
        self.label_4.setText(_translate("AutoTune", "D: 100"))
        self.ok_autotune.setText(_translate("AutoTune", "OK"))
        self.cancel_autotune.setText(_translate("AutoTune", "CANCEL"))
