# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printer_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_Printer(object):
    def setupUi(self, New_Printer):
        New_Printer.setObjectName("New_Printer")
        New_Printer.resize(299, 149)
        New_Printer.setMinimumSize(QtCore.QSize(299, 140))
        New_Printer.setMaximumSize(QtCore.QSize(299, 149))
        New_Printer.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 63, 63);")
        self.frame_2 = QtWidgets.QFrame(New_Printer)
        self.frame_2.setGeometry(QtCore.QRect(9, 9, 281, 131))
        self.frame_2.setMinimumSize(QtCore.QSize(281, 131))
        self.frame_2.setMaximumSize(QtCore.QSize(281, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(95, 10, 90, 18))
        self.label.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(40, 34, 200, 50))
        self.frame_3.setMinimumSize(QtCore.QSize(200, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(200, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.input_name = QtWidgets.QPlainTextEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_name.sizePolicy().hasHeightForWidth())
        self.input_name.setSizePolicy(sizePolicy)
        self.input_name.setMinimumSize(QtCore.QSize(180, 25))
        self.input_name.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_name.setFont(font)
        self.input_name.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:3px;\n"
"border-width:1px; \n"
"border-color:white;\n"
"}\n"
"QPlainTextEdit:hover{\n"
"border-color: rgb(85, 170, 255);\n"
"}\n"
"QPlainTextEdit:focus{\n"
"border-color: rgb(85, 170, 255);\n"
"}\n"
"QPlainTextEdit:disabled {\n"
"background-color: rgb(63, 63, 63);\n"
"color: rgb(0, 0, 0);\n"
"border-color:rgb(120, 120, 120)\n"
"}")
        self.input_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input_name.setObjectName("input_name")
        self.gridLayout.addWidget(self.input_name, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(30, 81, 220, 40))
        self.frame_4.setMinimumSize(QtCore.QSize(220, 40))
        self.frame_4.setMaximumSize(QtCore.QSize(220, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_printer = QtWidgets.QPushButton(self.frame_4)
        self.ok_printer.setMinimumSize(QtCore.QSize(80, 25))
        self.ok_printer.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ok_printer.setFont(font)
        self.ok_printer.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.ok_printer.setObjectName("ok_printer")
        self.horizontalLayout.addWidget(self.ok_printer)
        self.cancel_printer = QtWidgets.QPushButton(self.frame_4)
        self.cancel_printer.setMinimumSize(QtCore.QSize(80, 25))
        self.cancel_printer.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_printer.setFont(font)
        self.cancel_printer.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.cancel_printer.setObjectName("cancel_printer")
        self.horizontalLayout.addWidget(self.cancel_printer)

        self.retranslateUi(New_Printer)
        QtCore.QMetaObject.connectSlotsByName(New_Printer)

    def retranslateUi(self, New_Printer):
        _translate = QtCore.QCoreApplication.translate
        New_Printer.setWindowTitle(_translate("New_Printer", "Form"))
        self.label.setText(_translate("New_Printer", "Printer Name:"))
        self.ok_printer.setText(_translate("New_Printer", "OK"))
        self.cancel_printer.setText(_translate("New_Printer", "CANCEL"))
