# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pinswindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pinswindow(object):
    def setupUi(self, pinswindow):
        pinswindow.setObjectName("pinswindow")
        pinswindow.resize(680, 410)
        pinswindow.setMinimumSize(QtCore.QSize(680, 410))
        pinswindow.setMaximumSize(QtCore.QSize(680, 410))
        pinswindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(47, 47, 47);")
        self.groupBox = QtWidgets.QGroupBox(pinswindow)
        self.groupBox.setGeometry(QtCore.QRect(65, 30, 541, 341))
        self.groupBox.setMaximumSize(QtCore.QSize(550, 350))
        self.groupBox.setStyleSheet("QGroupBox  {\n"
"    color: white;\n"
"    border-style: solid;    \n"
"    border-width:2px; \n"
"    border-color:    rgb(82,82,82);\n"
"    border-radius:5px;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pin0 = QtWidgets.QPushButton(self.groupBox)
        self.pin0.setEnabled(True)
        self.pin0.setMinimumSize(QtCore.QSize(30, 30))
        self.pin0.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin0.setFont(font)
        self.pin0.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin0.setObjectName("pin0")
        self.gridLayout.addWidget(self.pin0, 0, 0, 1, 1)
        self.pin1 = QtWidgets.QPushButton(self.groupBox)
        self.pin1.setEnabled(True)
        self.pin1.setMinimumSize(QtCore.QSize(30, 30))
        self.pin1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin1.setFont(font)
        self.pin1.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin1.setObjectName("pin1")
        self.gridLayout.addWidget(self.pin1, 0, 1, 1, 1)
        self.pin2 = QtWidgets.QPushButton(self.groupBox)
        self.pin2.setEnabled(True)
        self.pin2.setMinimumSize(QtCore.QSize(30, 30))
        self.pin2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin2.setFont(font)
        self.pin2.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin2.setObjectName("pin2")
        self.gridLayout.addWidget(self.pin2, 0, 2, 1, 1)
        self.pin3 = QtWidgets.QPushButton(self.groupBox)
        self.pin3.setEnabled(True)
        self.pin3.setMinimumSize(QtCore.QSize(30, 30))
        self.pin3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin3.setFont(font)
        self.pin3.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin3.setObjectName("pin3")
        self.gridLayout.addWidget(self.pin3, 0, 3, 1, 1)
        self.pin4 = QtWidgets.QPushButton(self.groupBox)
        self.pin4.setEnabled(True)
        self.pin4.setMinimumSize(QtCore.QSize(30, 30))
        self.pin4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin4.setFont(font)
        self.pin4.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin4.setObjectName("pin4")
        self.gridLayout.addWidget(self.pin4, 0, 4, 1, 1)
        self.pin5 = QtWidgets.QPushButton(self.groupBox)
        self.pin5.setEnabled(True)
        self.pin5.setMinimumSize(QtCore.QSize(30, 30))
        self.pin5.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin5.setFont(font)
        self.pin5.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin5.setObjectName("pin5")
        self.gridLayout.addWidget(self.pin5, 0, 5, 1, 1)
        self.pin6 = QtWidgets.QPushButton(self.groupBox)
        self.pin6.setEnabled(True)
        self.pin6.setMinimumSize(QtCore.QSize(30, 30))
        self.pin6.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin6.setFont(font)
        self.pin6.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin6.setObjectName("pin6")
        self.gridLayout.addWidget(self.pin6, 0, 6, 1, 1)
        self.pin7 = QtWidgets.QPushButton(self.groupBox)
        self.pin7.setEnabled(True)
        self.pin7.setMinimumSize(QtCore.QSize(30, 30))
        self.pin7.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin7.setFont(font)
        self.pin7.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin7.setObjectName("pin7")
        self.gridLayout.addWidget(self.pin7, 0, 7, 1, 1)
        self.pin8 = QtWidgets.QPushButton(self.groupBox)
        self.pin8.setEnabled(True)
        self.pin8.setMinimumSize(QtCore.QSize(30, 30))
        self.pin8.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin8.setFont(font)
        self.pin8.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin8.setObjectName("pin8")
        self.gridLayout.addWidget(self.pin8, 0, 8, 1, 1)
        self.pin9 = QtWidgets.QPushButton(self.groupBox)
        self.pin9.setEnabled(True)
        self.pin9.setMinimumSize(QtCore.QSize(30, 30))
        self.pin9.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin9.setFont(font)
        self.pin9.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin9.setObjectName("pin9")
        self.gridLayout.addWidget(self.pin9, 1, 0, 1, 1)
        self.pin10 = QtWidgets.QPushButton(self.groupBox)
        self.pin10.setEnabled(True)
        self.pin10.setMinimumSize(QtCore.QSize(30, 30))
        self.pin10.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin10.setFont(font)
        self.pin10.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin10.setObjectName("pin10")
        self.gridLayout.addWidget(self.pin10, 1, 1, 1, 1)
        self.pin11 = QtWidgets.QPushButton(self.groupBox)
        self.pin11.setEnabled(True)
        self.pin11.setMinimumSize(QtCore.QSize(30, 30))
        self.pin11.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin11.setFont(font)
        self.pin11.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin11.setObjectName("pin11")
        self.gridLayout.addWidget(self.pin11, 1, 2, 1, 1)
        self.pin12 = QtWidgets.QPushButton(self.groupBox)
        self.pin12.setEnabled(True)
        self.pin12.setMinimumSize(QtCore.QSize(30, 30))
        self.pin12.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin12.setFont(font)
        self.pin12.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin12.setObjectName("pin12")
        self.gridLayout.addWidget(self.pin12, 1, 3, 1, 1)
        self.pin13 = QtWidgets.QPushButton(self.groupBox)
        self.pin13.setEnabled(True)
        self.pin13.setMinimumSize(QtCore.QSize(30, 30))
        self.pin13.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin13.setFont(font)
        self.pin13.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin13.setObjectName("pin13")
        self.gridLayout.addWidget(self.pin13, 1, 4, 1, 1)
        self.pin14 = QtWidgets.QPushButton(self.groupBox)
        self.pin14.setEnabled(True)
        self.pin14.setMinimumSize(QtCore.QSize(30, 30))
        self.pin14.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin14.setFont(font)
        self.pin14.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin14.setObjectName("pin14")
        self.gridLayout.addWidget(self.pin14, 1, 5, 1, 1)
        self.pin15 = QtWidgets.QPushButton(self.groupBox)
        self.pin15.setEnabled(True)
        self.pin15.setMinimumSize(QtCore.QSize(30, 30))
        self.pin15.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin15.setFont(font)
        self.pin15.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin15.setObjectName("pin15")
        self.gridLayout.addWidget(self.pin15, 1, 6, 1, 1)
        self.pin16 = QtWidgets.QPushButton(self.groupBox)
        self.pin16.setEnabled(True)
        self.pin16.setMinimumSize(QtCore.QSize(30, 30))
        self.pin16.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin16.setFont(font)
        self.pin16.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin16.setObjectName("pin16")
        self.gridLayout.addWidget(self.pin16, 1, 7, 1, 1)
        self.pin17 = QtWidgets.QPushButton(self.groupBox)
        self.pin17.setEnabled(True)
        self.pin17.setMinimumSize(QtCore.QSize(30, 30))
        self.pin17.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin17.setFont(font)
        self.pin17.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin17.setObjectName("pin17")
        self.gridLayout.addWidget(self.pin17, 1, 8, 1, 1)
        self.pin18 = QtWidgets.QPushButton(self.groupBox)
        self.pin18.setEnabled(True)
        self.pin18.setMinimumSize(QtCore.QSize(30, 30))
        self.pin18.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin18.setFont(font)
        self.pin18.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin18.setObjectName("pin18")
        self.gridLayout.addWidget(self.pin18, 2, 0, 1, 1)
        self.pin19 = QtWidgets.QPushButton(self.groupBox)
        self.pin19.setEnabled(True)
        self.pin19.setMinimumSize(QtCore.QSize(30, 30))
        self.pin19.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin19.setFont(font)
        self.pin19.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin19.setObjectName("pin19")
        self.gridLayout.addWidget(self.pin19, 2, 1, 1, 1)
        self.pin20 = QtWidgets.QPushButton(self.groupBox)
        self.pin20.setEnabled(True)
        self.pin20.setMinimumSize(QtCore.QSize(30, 30))
        self.pin20.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin20.setFont(font)
        self.pin20.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin20.setObjectName("pin20")
        self.gridLayout.addWidget(self.pin20, 2, 2, 1, 1)
        self.pin21 = QtWidgets.QPushButton(self.groupBox)
        self.pin21.setEnabled(True)
        self.pin21.setMinimumSize(QtCore.QSize(30, 30))
        self.pin21.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin21.setFont(font)
        self.pin21.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin21.setObjectName("pin21")
        self.gridLayout.addWidget(self.pin21, 2, 3, 1, 1)
        self.pin22 = QtWidgets.QPushButton(self.groupBox)
        self.pin22.setEnabled(True)
        self.pin22.setMinimumSize(QtCore.QSize(30, 30))
        self.pin22.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin22.setFont(font)
        self.pin22.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin22.setObjectName("pin22")
        self.gridLayout.addWidget(self.pin22, 2, 4, 1, 1)
        self.pin23 = QtWidgets.QPushButton(self.groupBox)
        self.pin23.setEnabled(True)
        self.pin23.setMinimumSize(QtCore.QSize(30, 30))
        self.pin23.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin23.setFont(font)
        self.pin23.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin23.setObjectName("pin23")
        self.gridLayout.addWidget(self.pin23, 2, 5, 1, 1)
        self.pin24 = QtWidgets.QPushButton(self.groupBox)
        self.pin24.setEnabled(True)
        self.pin24.setMinimumSize(QtCore.QSize(30, 30))
        self.pin24.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin24.setFont(font)
        self.pin24.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin24.setObjectName("pin24")
        self.gridLayout.addWidget(self.pin24, 2, 6, 1, 1)
        self.pin25 = QtWidgets.QPushButton(self.groupBox)
        self.pin25.setEnabled(True)
        self.pin25.setMinimumSize(QtCore.QSize(30, 30))
        self.pin25.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin25.setFont(font)
        self.pin25.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin25.setObjectName("pin25")
        self.gridLayout.addWidget(self.pin25, 2, 7, 1, 1)
        self.pin26 = QtWidgets.QPushButton(self.groupBox)
        self.pin26.setEnabled(True)
        self.pin26.setMinimumSize(QtCore.QSize(30, 30))
        self.pin26.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin26.setFont(font)
        self.pin26.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin26.setObjectName("pin26")
        self.gridLayout.addWidget(self.pin26, 2, 8, 1, 1)
        self.pin27 = QtWidgets.QPushButton(self.groupBox)
        self.pin27.setEnabled(True)
        self.pin27.setMinimumSize(QtCore.QSize(30, 30))
        self.pin27.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin27.setFont(font)
        self.pin27.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin27.setObjectName("pin27")
        self.gridLayout.addWidget(self.pin27, 3, 0, 1, 1)
        self.pin28 = QtWidgets.QPushButton(self.groupBox)
        self.pin28.setEnabled(True)
        self.pin28.setMinimumSize(QtCore.QSize(30, 30))
        self.pin28.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin28.setFont(font)
        self.pin28.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin28.setObjectName("pin28")
        self.gridLayout.addWidget(self.pin28, 3, 1, 1, 1)
        self.pin29 = QtWidgets.QPushButton(self.groupBox)
        self.pin29.setEnabled(True)
        self.pin29.setMinimumSize(QtCore.QSize(30, 30))
        self.pin29.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin29.setFont(font)
        self.pin29.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin29.setObjectName("pin29")
        self.gridLayout.addWidget(self.pin29, 3, 2, 1, 1)
        self.pin30 = QtWidgets.QPushButton(self.groupBox)
        self.pin30.setEnabled(True)
        self.pin30.setMinimumSize(QtCore.QSize(30, 30))
        self.pin30.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin30.setFont(font)
        self.pin30.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin30.setObjectName("pin30")
        self.gridLayout.addWidget(self.pin30, 3, 3, 1, 1)
        self.pin31 = QtWidgets.QPushButton(self.groupBox)
        self.pin31.setEnabled(True)
        self.pin31.setMinimumSize(QtCore.QSize(30, 30))
        self.pin31.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin31.setFont(font)
        self.pin31.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin31.setObjectName("pin31")
        self.gridLayout.addWidget(self.pin31, 3, 4, 1, 1)
        self.pin32 = QtWidgets.QPushButton(self.groupBox)
        self.pin32.setEnabled(True)
        self.pin32.setMinimumSize(QtCore.QSize(30, 30))
        self.pin32.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin32.setFont(font)
        self.pin32.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin32.setObjectName("pin32")
        self.gridLayout.addWidget(self.pin32, 3, 5, 1, 1)
        self.pin33 = QtWidgets.QPushButton(self.groupBox)
        self.pin33.setEnabled(True)
        self.pin33.setMinimumSize(QtCore.QSize(30, 30))
        self.pin33.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin33.setFont(font)
        self.pin33.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin33.setObjectName("pin33")
        self.gridLayout.addWidget(self.pin33, 3, 6, 1, 1)
        self.pin34 = QtWidgets.QPushButton(self.groupBox)
        self.pin34.setEnabled(True)
        self.pin34.setMinimumSize(QtCore.QSize(30, 30))
        self.pin34.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin34.setFont(font)
        self.pin34.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin34.setObjectName("pin34")
        self.gridLayout.addWidget(self.pin34, 3, 7, 1, 1)
        self.pin35 = QtWidgets.QPushButton(self.groupBox)
        self.pin35.setEnabled(True)
        self.pin35.setMinimumSize(QtCore.QSize(30, 30))
        self.pin35.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin35.setFont(font)
        self.pin35.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin35.setObjectName("pin35")
        self.gridLayout.addWidget(self.pin35, 3, 8, 1, 1)
        self.pin36 = QtWidgets.QPushButton(self.groupBox)
        self.pin36.setEnabled(True)
        self.pin36.setMinimumSize(QtCore.QSize(30, 30))
        self.pin36.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin36.setFont(font)
        self.pin36.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin36.setObjectName("pin36")
        self.gridLayout.addWidget(self.pin36, 4, 0, 1, 1)
        self.pin37 = QtWidgets.QPushButton(self.groupBox)
        self.pin37.setEnabled(True)
        self.pin37.setMinimumSize(QtCore.QSize(30, 30))
        self.pin37.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin37.setFont(font)
        self.pin37.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin37.setObjectName("pin37")
        self.gridLayout.addWidget(self.pin37, 4, 1, 1, 1)
        self.pin38 = QtWidgets.QPushButton(self.groupBox)
        self.pin38.setEnabled(True)
        self.pin38.setMinimumSize(QtCore.QSize(30, 30))
        self.pin38.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin38.setFont(font)
        self.pin38.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin38.setObjectName("pin38")
        self.gridLayout.addWidget(self.pin38, 4, 2, 1, 1)
        self.pin39 = QtWidgets.QPushButton(self.groupBox)
        self.pin39.setEnabled(True)
        self.pin39.setMinimumSize(QtCore.QSize(30, 30))
        self.pin39.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin39.setFont(font)
        self.pin39.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin39.setObjectName("pin39")
        self.gridLayout.addWidget(self.pin39, 4, 3, 1, 1)
        self.pin40 = QtWidgets.QPushButton(self.groupBox)
        self.pin40.setEnabled(True)
        self.pin40.setMinimumSize(QtCore.QSize(30, 30))
        self.pin40.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin40.setFont(font)
        self.pin40.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin40.setObjectName("pin40")
        self.gridLayout.addWidget(self.pin40, 4, 4, 1, 1)
        self.pin41 = QtWidgets.QPushButton(self.groupBox)
        self.pin41.setEnabled(True)
        self.pin41.setMinimumSize(QtCore.QSize(30, 30))
        self.pin41.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin41.setFont(font)
        self.pin41.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin41.setObjectName("pin41")
        self.gridLayout.addWidget(self.pin41, 4, 5, 1, 1)
        self.pin42 = QtWidgets.QPushButton(self.groupBox)
        self.pin42.setEnabled(True)
        self.pin42.setMinimumSize(QtCore.QSize(30, 30))
        self.pin42.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin42.setFont(font)
        self.pin42.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin42.setObjectName("pin42")
        self.gridLayout.addWidget(self.pin42, 4, 6, 1, 1)
        self.pin43 = QtWidgets.QPushButton(self.groupBox)
        self.pin43.setEnabled(True)
        self.pin43.setMinimumSize(QtCore.QSize(30, 30))
        self.pin43.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin43.setFont(font)
        self.pin43.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin43.setObjectName("pin43")
        self.gridLayout.addWidget(self.pin43, 4, 7, 1, 1)
        self.pin44 = QtWidgets.QPushButton(self.groupBox)
        self.pin44.setEnabled(True)
        self.pin44.setMinimumSize(QtCore.QSize(30, 30))
        self.pin44.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin44.setFont(font)
        self.pin44.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin44.setObjectName("pin44")
        self.gridLayout.addWidget(self.pin44, 4, 8, 1, 1)
        self.pin45 = QtWidgets.QPushButton(self.groupBox)
        self.pin45.setEnabled(True)
        self.pin45.setMinimumSize(QtCore.QSize(30, 30))
        self.pin45.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin45.setFont(font)
        self.pin45.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin45.setObjectName("pin45")
        self.gridLayout.addWidget(self.pin45, 5, 0, 1, 1)
        self.pin46 = QtWidgets.QPushButton(self.groupBox)
        self.pin46.setEnabled(True)
        self.pin46.setMinimumSize(QtCore.QSize(30, 30))
        self.pin46.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin46.setFont(font)
        self.pin46.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin46.setObjectName("pin46")
        self.gridLayout.addWidget(self.pin46, 5, 1, 1, 1)
        self.pin47 = QtWidgets.QPushButton(self.groupBox)
        self.pin47.setEnabled(True)
        self.pin47.setMinimumSize(QtCore.QSize(30, 30))
        self.pin47.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin47.setFont(font)
        self.pin47.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin47.setObjectName("pin47")
        self.gridLayout.addWidget(self.pin47, 5, 2, 1, 1)
        self.pin48 = QtWidgets.QPushButton(self.groupBox)
        self.pin48.setEnabled(True)
        self.pin48.setMinimumSize(QtCore.QSize(30, 30))
        self.pin48.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin48.setFont(font)
        self.pin48.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin48.setObjectName("pin48")
        self.gridLayout.addWidget(self.pin48, 5, 3, 1, 1)
        self.pin49 = QtWidgets.QPushButton(self.groupBox)
        self.pin49.setEnabled(True)
        self.pin49.setMinimumSize(QtCore.QSize(30, 30))
        self.pin49.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin49.setFont(font)
        self.pin49.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin49.setObjectName("pin49")
        self.gridLayout.addWidget(self.pin49, 5, 4, 1, 1)
        self.pin50 = QtWidgets.QPushButton(self.groupBox)
        self.pin50.setEnabled(True)
        self.pin50.setMinimumSize(QtCore.QSize(30, 30))
        self.pin50.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin50.setFont(font)
        self.pin50.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin50.setObjectName("pin50")
        self.gridLayout.addWidget(self.pin50, 5, 5, 1, 1)
        self.pin51 = QtWidgets.QPushButton(self.groupBox)
        self.pin51.setEnabled(True)
        self.pin51.setMinimumSize(QtCore.QSize(30, 30))
        self.pin51.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin51.setFont(font)
        self.pin51.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin51.setObjectName("pin51")
        self.gridLayout.addWidget(self.pin51, 5, 6, 1, 1)
        self.pin52 = QtWidgets.QPushButton(self.groupBox)
        self.pin52.setEnabled(True)
        self.pin52.setMinimumSize(QtCore.QSize(30, 30))
        self.pin52.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin52.setFont(font)
        self.pin52.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin52.setObjectName("pin52")
        self.gridLayout.addWidget(self.pin52, 5, 7, 1, 1)
        self.pin53 = QtWidgets.QPushButton(self.groupBox)
        self.pin53.setEnabled(True)
        self.pin53.setMinimumSize(QtCore.QSize(30, 30))
        self.pin53.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin53.setFont(font)
        self.pin53.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin53.setObjectName("pin53")
        self.gridLayout.addWidget(self.pin53, 5, 8, 1, 1)
        self.pin54 = QtWidgets.QPushButton(self.groupBox)
        self.pin54.setEnabled(True)
        self.pin54.setMinimumSize(QtCore.QSize(30, 30))
        self.pin54.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin54.setFont(font)
        self.pin54.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin54.setObjectName("pin54")
        self.gridLayout.addWidget(self.pin54, 6, 0, 1, 1)
        self.pin55 = QtWidgets.QPushButton(self.groupBox)
        self.pin55.setEnabled(True)
        self.pin55.setMinimumSize(QtCore.QSize(30, 30))
        self.pin55.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin55.setFont(font)
        self.pin55.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin55.setObjectName("pin55")
        self.gridLayout.addWidget(self.pin55, 6, 1, 1, 1)
        self.pin56 = QtWidgets.QPushButton(self.groupBox)
        self.pin56.setEnabled(True)
        self.pin56.setMinimumSize(QtCore.QSize(30, 30))
        self.pin56.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin56.setFont(font)
        self.pin56.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin56.setObjectName("pin56")
        self.gridLayout.addWidget(self.pin56, 6, 2, 1, 1)
        self.pin57 = QtWidgets.QPushButton(self.groupBox)
        self.pin57.setEnabled(True)
        self.pin57.setMinimumSize(QtCore.QSize(30, 30))
        self.pin57.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin57.setFont(font)
        self.pin57.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin57.setObjectName("pin57")
        self.gridLayout.addWidget(self.pin57, 6, 3, 1, 1)
        self.pin58 = QtWidgets.QPushButton(self.groupBox)
        self.pin58.setEnabled(True)
        self.pin58.setMinimumSize(QtCore.QSize(30, 30))
        self.pin58.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin58.setFont(font)
        self.pin58.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin58.setObjectName("pin58")
        self.gridLayout.addWidget(self.pin58, 6, 4, 1, 1)
        self.pin59 = QtWidgets.QPushButton(self.groupBox)
        self.pin59.setEnabled(True)
        self.pin59.setMinimumSize(QtCore.QSize(30, 30))
        self.pin59.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin59.setFont(font)
        self.pin59.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin59.setObjectName("pin59")
        self.gridLayout.addWidget(self.pin59, 6, 5, 1, 1)
        self.pin60 = QtWidgets.QPushButton(self.groupBox)
        self.pin60.setEnabled(True)
        self.pin60.setMinimumSize(QtCore.QSize(30, 30))
        self.pin60.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin60.setFont(font)
        self.pin60.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin60.setObjectName("pin60")
        self.gridLayout.addWidget(self.pin60, 6, 6, 1, 1)
        self.pin61 = QtWidgets.QPushButton(self.groupBox)
        self.pin61.setEnabled(True)
        self.pin61.setMinimumSize(QtCore.QSize(30, 30))
        self.pin61.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin61.setFont(font)
        self.pin61.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin61.setObjectName("pin61")
        self.gridLayout.addWidget(self.pin61, 6, 7, 1, 1)
        self.pin62 = QtWidgets.QPushButton(self.groupBox)
        self.pin62.setEnabled(True)
        self.pin62.setMinimumSize(QtCore.QSize(30, 30))
        self.pin62.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin62.setFont(font)
        self.pin62.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin62.setObjectName("pin62")
        self.gridLayout.addWidget(self.pin62, 6, 8, 1, 1)
        self.pin63 = QtWidgets.QPushButton(self.groupBox)
        self.pin63.setEnabled(True)
        self.pin63.setMinimumSize(QtCore.QSize(30, 30))
        self.pin63.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin63.setFont(font)
        self.pin63.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin63.setObjectName("pin63")
        self.gridLayout.addWidget(self.pin63, 7, 0, 1, 1)
        self.pin64 = QtWidgets.QPushButton(self.groupBox)
        self.pin64.setEnabled(True)
        self.pin64.setMinimumSize(QtCore.QSize(30, 30))
        self.pin64.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin64.setFont(font)
        self.pin64.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin64.setObjectName("pin64")
        self.gridLayout.addWidget(self.pin64, 7, 1, 1, 1)
        self.pin65 = QtWidgets.QPushButton(self.groupBox)
        self.pin65.setEnabled(True)
        self.pin65.setMinimumSize(QtCore.QSize(30, 30))
        self.pin65.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin65.setFont(font)
        self.pin65.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin65.setObjectName("pin65")
        self.gridLayout.addWidget(self.pin65, 7, 2, 1, 1)
        self.pin66 = QtWidgets.QPushButton(self.groupBox)
        self.pin66.setEnabled(True)
        self.pin66.setMinimumSize(QtCore.QSize(30, 30))
        self.pin66.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin66.setFont(font)
        self.pin66.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin66.setObjectName("pin66")
        self.gridLayout.addWidget(self.pin66, 7, 3, 1, 1)
        self.pin67 = QtWidgets.QPushButton(self.groupBox)
        self.pin67.setEnabled(True)
        self.pin67.setMinimumSize(QtCore.QSize(30, 30))
        self.pin67.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin67.setFont(font)
        self.pin67.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin67.setObjectName("pin67")
        self.gridLayout.addWidget(self.pin67, 7, 4, 1, 1)
        self.pin68 = QtWidgets.QPushButton(self.groupBox)
        self.pin68.setEnabled(True)
        self.pin68.setMinimumSize(QtCore.QSize(30, 30))
        self.pin68.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin68.setFont(font)
        self.pin68.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin68.setObjectName("pin68")
        self.gridLayout.addWidget(self.pin68, 7, 5, 1, 1)
        self.pin69 = QtWidgets.QPushButton(self.groupBox)
        self.pin69.setEnabled(True)
        self.pin69.setMinimumSize(QtCore.QSize(30, 30))
        self.pin69.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin69.setFont(font)
        self.pin69.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin69.setObjectName("pin69")
        self.gridLayout.addWidget(self.pin69, 7, 6, 1, 1)
        self.pin70 = QtWidgets.QPushButton(self.groupBox)
        self.pin70.setEnabled(True)
        self.pin70.setMinimumSize(QtCore.QSize(30, 30))
        self.pin70.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pin70.setFont(font)
        self.pin70.setStyleSheet("QPushButton {\n"
"background-color:rgb(47, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius:5px;\n"
"border-width:2px; \n"
"border-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:hover {\n"
"border-width:3px; \n"
"border-color:rgb(255, 115, 30);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:rgb(255, 115, 30);\n"
"border-color: rgb(255, 195, 110);\n"
"border-width: 4px;     \n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(255, 149, 62);\n"
"color: rgb(83, 83, 83);\n"
"border-color:rgb(83, 83, 83);\n"
"}\n"
"\n"
"")
        self.pin70.setObjectName("pin70")
        self.gridLayout.addWidget(self.pin70, 7, 8, 1, 1)

        self.retranslateUi(pinswindow)
        QtCore.QMetaObject.connectSlotsByName(pinswindow)

    def retranslateUi(self, pinswindow):
        _translate = QtCore.QCoreApplication.translate
        pinswindow.setWindowTitle(_translate("pinswindow", "Form"))
        self.groupBox.setTitle(_translate("pinswindow", "Select Pin"))
        self.pin0.setText(_translate("pinswindow", "0"))
        self.pin1.setText(_translate("pinswindow", "1"))
        self.pin2.setText(_translate("pinswindow", "2"))
        self.pin3.setText(_translate("pinswindow", "3"))
        self.pin4.setText(_translate("pinswindow", "4"))
        self.pin5.setText(_translate("pinswindow", "5"))
        self.pin6.setText(_translate("pinswindow", "6"))
        self.pin7.setText(_translate("pinswindow", "7"))
        self.pin8.setText(_translate("pinswindow", "8"))
        self.pin9.setText(_translate("pinswindow", "9"))
        self.pin10.setText(_translate("pinswindow", "10"))
        self.pin11.setText(_translate("pinswindow", "11"))
        self.pin12.setText(_translate("pinswindow", "12"))
        self.pin13.setText(_translate("pinswindow", "13"))
        self.pin14.setText(_translate("pinswindow", "14"))
        self.pin15.setText(_translate("pinswindow", "15"))
        self.pin16.setText(_translate("pinswindow", "16"))
        self.pin17.setText(_translate("pinswindow", "17"))
        self.pin18.setText(_translate("pinswindow", "18"))
        self.pin19.setText(_translate("pinswindow", "19"))
        self.pin20.setText(_translate("pinswindow", "20"))
        self.pin21.setText(_translate("pinswindow", "21"))
        self.pin22.setText(_translate("pinswindow", "22"))
        self.pin23.setText(_translate("pinswindow", "23"))
        self.pin24.setText(_translate("pinswindow", "24"))
        self.pin25.setText(_translate("pinswindow", "25"))
        self.pin26.setText(_translate("pinswindow", "26"))
        self.pin27.setText(_translate("pinswindow", "27"))
        self.pin28.setText(_translate("pinswindow", "28"))
        self.pin29.setText(_translate("pinswindow", "29"))
        self.pin30.setText(_translate("pinswindow", "30"))
        self.pin31.setText(_translate("pinswindow", "31"))
        self.pin32.setText(_translate("pinswindow", "32"))
        self.pin33.setText(_translate("pinswindow", "33"))
        self.pin34.setText(_translate("pinswindow", "34"))
        self.pin35.setText(_translate("pinswindow", "35"))
        self.pin36.setText(_translate("pinswindow", "36"))
        self.pin37.setText(_translate("pinswindow", "37"))
        self.pin38.setText(_translate("pinswindow", "38"))
        self.pin39.setText(_translate("pinswindow", "39"))
        self.pin40.setText(_translate("pinswindow", "40"))
        self.pin41.setText(_translate("pinswindow", "41"))
        self.pin42.setText(_translate("pinswindow", "42"))
        self.pin43.setText(_translate("pinswindow", "43"))
        self.pin44.setText(_translate("pinswindow", "44"))
        self.pin45.setText(_translate("pinswindow", "45"))
        self.pin46.setText(_translate("pinswindow", "46"))
        self.pin47.setText(_translate("pinswindow", "47"))
        self.pin48.setText(_translate("pinswindow", "48"))
        self.pin49.setText(_translate("pinswindow", "49"))
        self.pin50.setText(_translate("pinswindow", "50"))
        self.pin51.setText(_translate("pinswindow", "51"))
        self.pin52.setText(_translate("pinswindow", "52"))
        self.pin53.setText(_translate("pinswindow", "53"))
        self.pin54.setText(_translate("pinswindow", "54"))
        self.pin55.setText(_translate("pinswindow", "55"))
        self.pin56.setText(_translate("pinswindow", "56"))
        self.pin57.setText(_translate("pinswindow", "57"))
        self.pin58.setText(_translate("pinswindow", "58"))
        self.pin59.setText(_translate("pinswindow", "59"))
        self.pin60.setText(_translate("pinswindow", "60"))
        self.pin61.setText(_translate("pinswindow", "61"))
        self.pin62.setText(_translate("pinswindow", "62"))
        self.pin63.setText(_translate("pinswindow", "63"))
        self.pin64.setText(_translate("pinswindow", "64"))
        self.pin65.setText(_translate("pinswindow", "65"))
        self.pin66.setText(_translate("pinswindow", "66"))
        self.pin67.setText(_translate("pinswindow", "67"))
        self.pin68.setText(_translate("pinswindow", "68"))
        self.pin69.setText(_translate("pinswindow", "69"))
        self.pin70.setText(_translate("pinswindow", "N"))
